# Generated by Django 4.1.1 on 2022-10-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='contruido_por',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
