# Generated by Django 4.1.1 on 2022-11-08 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Configuracion',
        ),
    ]
